---
apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      run: nginx-basic
   name: nginx-basic
spec:
   replicas: 2
   selector:
     matchLabels:
       run: nginx-basic
   template:
     metadata:
        labels:
          run: nginx-basic
     spec:
        containers:
          - image: cssp007143/nginx-basic:${build_number}
            name:  nginx-basic
            ports:
              - containerPort: 80
            
---

apiVersion: v1
kind: Service
metadata:
  name: for-nginx-basic
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
  selector:
    run: nginx-basic
